---
# tasks file for atom
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Fedora.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

#- debug: msg="test"
